# Generated by Django 3.2.11 on 2023-01-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=64)),
                ('_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用戶資料庫',
                'verbose_name_plural': '用戶資料庫',
                'ordering': ['-_time'],
            },
        ),
    ]
